// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/csqlgrpc/sql_data_service.proto

package csqlgrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error reasons for `StreamSqlData`.
// Typically used with standard error codes, with the error info/reason field
// set to the string representation of the enum value.
type StreamSqlDataErrorReason int32

const (
	// Indicates that the error reason is unknown.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_UNKNOWN StreamSqlDataErrorReason = 0
	// Indicates that the operation is not supported for given instance type.
	// Typically used with error code `google.rpc.Code.FAILED_PRECONDITION`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE StreamSqlDataErrorReason = 1
)

// Enum value maps for StreamSqlDataErrorReason.
var (
	StreamSqlDataErrorReason_name = map[int32]string{
		0: "STREAM_SQL_DATA_ERROR_REASON_UNKNOWN",
		1: "STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE",
	}
	StreamSqlDataErrorReason_value = map[string]int32{
		"STREAM_SQL_DATA_ERROR_REASON_UNKNOWN":                   0,
		"STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE": 1,
	}
)

func (x StreamSqlDataErrorReason) Enum() *StreamSqlDataErrorReason {
	p := new(StreamSqlDataErrorReason)
	*p = x
	return p
}

func (x StreamSqlDataErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamSqlDataErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_csqlgrpc_sql_data_service_proto_enumTypes[0].Descriptor()
}

func (StreamSqlDataErrorReason) Type() protoreflect.EnumType {
	return &file_internal_csqlgrpc_sql_data_service_proto_enumTypes[0]
}

func (x StreamSqlDataErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamSqlDataErrorReason.Descriptor instead.
func (StreamSqlDataErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{0}
}

// Message sent from the client to `SqlDataService`.
type StreamSqlDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `location_id` is used to route the request to a specific region. Use the
	// same region which was used to create the instance. Use the format
	// `locations/{location}`, for example: `locations/us-central1`.
	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	// The type of message sent within the stream.
	//
	// Types that are valid to be assigned to MessageType:
	//
	//	*StreamSqlDataRequest_ConnectionSettings
	//	*StreamSqlDataRequest_Payload
	MessageType   isStreamSqlDataRequest_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSqlDataRequest) Reset() {
	*x = StreamSqlDataRequest{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSqlDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSqlDataRequest) ProtoMessage() {}

func (x *StreamSqlDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSqlDataRequest.ProtoReflect.Descriptor instead.
func (*StreamSqlDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *StreamSqlDataRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *StreamSqlDataRequest) GetMessageType() isStreamSqlDataRequest_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *StreamSqlDataRequest) GetConnectionSettings() *ConnectionSettings {
	if x != nil {
		if x, ok := x.MessageType.(*StreamSqlDataRequest_ConnectionSettings); ok {
			return x.ConnectionSettings
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetPayload() *ClientPayload {
	if x != nil {
		if x, ok := x.MessageType.(*StreamSqlDataRequest_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isStreamSqlDataRequest_MessageType interface {
	isStreamSqlDataRequest_MessageType()
}

type StreamSqlDataRequest_ConnectionSettings struct {
	// Parameters for establishing the connection. MUST be sent as the first
	// message on the stream.
	ConnectionSettings *ConnectionSettings `protobuf:"bytes,2,opt,name=connection_settings,json=connectionSettings,proto3,oneof"`
}

type StreamSqlDataRequest_Payload struct {
	// Data to be forwarded to the database.
	Payload *ClientPayload `protobuf:"bytes,3,opt,name=payload,proto3,oneof"`
}

func (*StreamSqlDataRequest_ConnectionSettings) isStreamSqlDataRequest_MessageType() {}

func (*StreamSqlDataRequest_Payload) isStreamSqlDataRequest_MessageType() {}

// Initial connection parameters.
type ConnectionSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target of the connection.
	//
	// Types that are valid to be assigned to Target:
	//
	//	*ConnectionSettings_InstanceId
	Target        isConnectionSettings_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionSettings) Reset() {
	*x = ConnectionSettings{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSettings) ProtoMessage() {}

func (x *ConnectionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSettings.ProtoReflect.Descriptor instead.
func (*ConnectionSettings) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionSettings) GetTarget() isConnectionSettings_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ConnectionSettings) GetInstanceId() *InstanceId {
	if x != nil {
		if x, ok := x.Target.(*ConnectionSettings_InstanceId); ok {
			return x.InstanceId
		}
	}
	return nil
}

type isConnectionSettings_Target interface {
	isConnectionSettings_Target()
}

type ConnectionSettings_InstanceId struct {
	// The identifier of the Cloud SQL instance.
	InstanceId *InstanceId `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3,oneof"`
}

func (*ConnectionSettings_InstanceId) isConnectionSettings_Target() {}

// The identifier of the Cloud SQL instance.
type InstanceId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full resource name of the Cloud SQL instance, in the form:
	// `projects/{project}/instances/{instance}`, for example:
	// `projects/foo-project/instances/bar-instance`.
	Instance      string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceId) Reset() {
	*x = InstanceId{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceId) ProtoMessage() {}

func (x *InstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceId.ProtoReflect.Descriptor instead.
func (*InstanceId) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *InstanceId) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// Wrapper for data being sent to the database.
type ClientPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw data to be sent to the database. See the documentation for
	// `ProxySqlData` for details on the expected wire format.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPayload) Reset() {
	*x = ClientPayload{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPayload) ProtoMessage() {}

func (x *ClientPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPayload.ProtoReflect.Descriptor instead.
func (*ClientPayload) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClientPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message sent from `SqlDataService` back to the client.
type StreamSqlDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the message received from `SqlDataService`.
	//
	// Types that are valid to be assigned to Type:
	//
	//	*StreamSqlDataResponse_Payload
	Type          isStreamSqlDataResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSqlDataResponse) Reset() {
	*x = StreamSqlDataResponse{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSqlDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSqlDataResponse) ProtoMessage() {}

func (x *StreamSqlDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSqlDataResponse.ProtoReflect.Descriptor instead.
func (*StreamSqlDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *StreamSqlDataResponse) GetType() isStreamSqlDataResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *StreamSqlDataResponse) GetPayload() *ServerPayload {
	if x != nil {
		if x, ok := x.Type.(*StreamSqlDataResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isStreamSqlDataResponse_Type interface {
	isStreamSqlDataResponse_Type()
}

type StreamSqlDataResponse_Payload struct {
	// Raw data received from the database.
	Payload *ServerPayload `protobuf:"bytes,1,opt,name=payload,proto3,oneof"`
}

func (*StreamSqlDataResponse_Payload) isStreamSqlDataResponse_Type() {}

// Wrapper for data being received from the database.
type ServerPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw data received from the database. See the documentation for
	// `ProxySqlData` for details on the expected wire format.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPayload) Reset() {
	*x = ServerPayload{}
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPayload) ProtoMessage() {}

func (x *ServerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_csqlgrpc_sql_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPayload.ProtoReflect.Descriptor instead.
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServerPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_csqlgrpc_sql_data_service_proto protoreflect.FileDescriptor

const file_internal_csqlgrpc_sql_data_service_proto_rawDesc = "" +
	"\n" +
	"(internal/csqlgrpc/sql_data_service.proto\x12\x18google.cloud.sql.v1beta4\"\xed\x01\n" +
	"\x14StreamSqlDataRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12_\n" +
	"\x13connection_settings\x18\x02 \x01(\v2,.google.cloud.sql.v1beta4.ConnectionSettingsH\x00R\x12connectionSettings\x12C\n" +
	"\apayload\x18\x03 \x01(\v2'.google.cloud.sql.v1beta4.ClientPayloadH\x00R\apayloadB\x0e\n" +
	"\fmessage_type\"g\n" +
	"\x12ConnectionSettings\x12G\n" +
	"\vinstance_id\x18\x01 \x01(\v2$.google.cloud.sql.v1beta4.InstanceIdH\x00R\n" +
	"instanceIdB\b\n" +
	"\x06target\"(\n" +
	"\n" +
	"InstanceId\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"#\n" +
	"\rClientPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"d\n" +
	"\x15StreamSqlDataResponse\x12C\n" +
	"\apayload\x18\x01 \x01(\v2'.google.cloud.sql.v1beta4.ServerPayloadH\x00R\apayloadB\x06\n" +
	"\x04type\"#\n" +
	"\rServerPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\x80\x01\n" +
	"\x18StreamSqlDataErrorReason\x12(\n" +
	"$STREAM_SQL_DATA_ERROR_REASON_UNKNOWN\x10\x00\x12:\n" +
	"6STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE\x10\x012\x88\x01\n" +
	"\x0eSqlDataService\x12v\n" +
	"\rStreamSqlData\x12..google.cloud.sql.v1beta4.StreamSqlDataRequest\x1a/.google.cloud.sql.v1beta4.StreamSqlDataResponse\"\x00(\x010\x012\x8f\x01\n" +
	"\x15SqlDataServiceJavaPoC\x12v\n" +
	"\rStreamSqlData\x12..google.cloud.sql.v1beta4.StreamSqlDataRequest\x1a/.google.cloud.sql.v1beta4.StreamSqlDataResponse\"\x00(\x010\x012\x8a\x01\n" +
	"\x10SqlDataServiceV3\x12v\n" +
	"\rStreamSqlData\x12..google.cloud.sql.v1beta4.StreamSqlDataRequest\x1a/.google.cloud.sql.v1beta4.StreamSqlDataResponse\"\x00(\x010\x01BF\n" +
	"\x1ccom.google.cloud.sql.v1beta4B\x11CloudSqlDataProtoP\x01Z\x11internal/csqlgrpcb\x06proto3"

var (
	file_internal_csqlgrpc_sql_data_service_proto_rawDescOnce sync.Once
	file_internal_csqlgrpc_sql_data_service_proto_rawDescData []byte
)

func file_internal_csqlgrpc_sql_data_service_proto_rawDescGZIP() []byte {
	file_internal_csqlgrpc_sql_data_service_proto_rawDescOnce.Do(func() {
		file_internal_csqlgrpc_sql_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_csqlgrpc_sql_data_service_proto_rawDesc), len(file_internal_csqlgrpc_sql_data_service_proto_rawDesc)))
	})
	return file_internal_csqlgrpc_sql_data_service_proto_rawDescData
}

var file_internal_csqlgrpc_sql_data_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_csqlgrpc_sql_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_csqlgrpc_sql_data_service_proto_goTypes = []any{
	(StreamSqlDataErrorReason)(0), // 0: google.cloud.sql.v1beta4.StreamSqlDataErrorReason
	(*StreamSqlDataRequest)(nil),  // 1: google.cloud.sql.v1beta4.StreamSqlDataRequest
	(*ConnectionSettings)(nil),    // 2: google.cloud.sql.v1beta4.ConnectionSettings
	(*InstanceId)(nil),            // 3: google.cloud.sql.v1beta4.InstanceId
	(*ClientPayload)(nil),         // 4: google.cloud.sql.v1beta4.ClientPayload
	(*StreamSqlDataResponse)(nil), // 5: google.cloud.sql.v1beta4.StreamSqlDataResponse
	(*ServerPayload)(nil),         // 6: google.cloud.sql.v1beta4.ServerPayload
}
var file_internal_csqlgrpc_sql_data_service_proto_depIdxs = []int32{
	2, // 0: google.cloud.sql.v1beta4.StreamSqlDataRequest.connection_settings:type_name -> google.cloud.sql.v1beta4.ConnectionSettings
	4, // 1: google.cloud.sql.v1beta4.StreamSqlDataRequest.payload:type_name -> google.cloud.sql.v1beta4.ClientPayload
	3, // 2: google.cloud.sql.v1beta4.ConnectionSettings.instance_id:type_name -> google.cloud.sql.v1beta4.InstanceId
	6, // 3: google.cloud.sql.v1beta4.StreamSqlDataResponse.payload:type_name -> google.cloud.sql.v1beta4.ServerPayload
	1, // 4: google.cloud.sql.v1beta4.SqlDataService.StreamSqlData:input_type -> google.cloud.sql.v1beta4.StreamSqlDataRequest
	1, // 5: google.cloud.sql.v1beta4.SqlDataServiceJavaPoC.StreamSqlData:input_type -> google.cloud.sql.v1beta4.StreamSqlDataRequest
	1, // 6: google.cloud.sql.v1beta4.SqlDataServiceV3.StreamSqlData:input_type -> google.cloud.sql.v1beta4.StreamSqlDataRequest
	5, // 7: google.cloud.sql.v1beta4.SqlDataService.StreamSqlData:output_type -> google.cloud.sql.v1beta4.StreamSqlDataResponse
	5, // 8: google.cloud.sql.v1beta4.SqlDataServiceJavaPoC.StreamSqlData:output_type -> google.cloud.sql.v1beta4.StreamSqlDataResponse
	5, // 9: google.cloud.sql.v1beta4.SqlDataServiceV3.StreamSqlData:output_type -> google.cloud.sql.v1beta4.StreamSqlDataResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_csqlgrpc_sql_data_service_proto_init() }
func file_internal_csqlgrpc_sql_data_service_proto_init() {
	if File_internal_csqlgrpc_sql_data_service_proto != nil {
		return
	}
	file_internal_csqlgrpc_sql_data_service_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamSqlDataRequest_ConnectionSettings)(nil),
		(*StreamSqlDataRequest_Payload)(nil),
	}
	file_internal_csqlgrpc_sql_data_service_proto_msgTypes[1].OneofWrappers = []any{
		(*ConnectionSettings_InstanceId)(nil),
	}
	file_internal_csqlgrpc_sql_data_service_proto_msgTypes[4].OneofWrappers = []any{
		(*StreamSqlDataResponse_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_csqlgrpc_sql_data_service_proto_rawDesc), len(file_internal_csqlgrpc_sql_data_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_csqlgrpc_sql_data_service_proto_goTypes,
		DependencyIndexes: file_internal_csqlgrpc_sql_data_service_proto_depIdxs,
		EnumInfos:         file_internal_csqlgrpc_sql_data_service_proto_enumTypes,
		MessageInfos:      file_internal_csqlgrpc_sql_data_service_proto_msgTypes,
	}.Build()
	File_internal_csqlgrpc_sql_data_service_proto = out.File
	file_internal_csqlgrpc_sql_data_service_proto_goTypes = nil
	file_internal_csqlgrpc_sql_data_service_proto_depIdxs = nil
}
