// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: internal/csqlgrpc/sql_data_service.proto

package csqlgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SqlDataService_StreamSqlData_FullMethodName = "/google.cloud.sql.v1beta4.SqlDataService/StreamSqlData"
)

// SqlDataServiceClient is the client API for SqlDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceClient interface {
	// `StreamSqlData` establishes a bidirectional stream to a Cloud SQL instance,
	// and then streams data to and from the instance.
	//
	// The first message from the client MUST be a `StreamSqlDataRequest` request
	// with configuration settings, including required values for the
	// `connection_settings` field. Subsequent messages from the client may
	// contain the `payload` field.
	//
	// Messages from the server may contain the `payload` field.
	//
	// The `payload` fields of the request and response streams contain the raw
	// data of the database's native wire protocol (e.g., PostgreSQL wire
	// protocol). The database client is responsible for generating and parsing
	// this data.
	//
	// Any errors on initial connection (e.g., connection failure, authorization
	// issues, network problems) will result in the stream being terminated with
	// an appropriate RPC status exception.
	//
	// After a successful connection is made, if an error occurs, then the server
	// terminates connection and returns the appropriate RPC status exception.
	StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error)
}

type sqlDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlDataServiceClient(cc grpc.ClientConnInterface) SqlDataServiceClient {
	return &sqlDataServiceClient{cc}
}

func (c *sqlDataServiceClient) StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SqlDataService_ServiceDesc.Streams[0], SqlDataService_StreamSqlData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSqlDataRequest, StreamSqlDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataService_StreamSqlDataClient = grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataServiceServer is the server API for SqlDataService service.
// All implementations must embed UnimplementedSqlDataServiceServer
// for forward compatibility.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceServer interface {
	// `StreamSqlData` establishes a bidirectional stream to a Cloud SQL instance,
	// and then streams data to and from the instance.
	//
	// The first message from the client MUST be a `StreamSqlDataRequest` request
	// with configuration settings, including required values for the
	// `connection_settings` field. Subsequent messages from the client may
	// contain the `payload` field.
	//
	// Messages from the server may contain the `payload` field.
	//
	// The `payload` fields of the request and response streams contain the raw
	// data of the database's native wire protocol (e.g., PostgreSQL wire
	// protocol). The database client is responsible for generating and parsing
	// this data.
	//
	// Any errors on initial connection (e.g., connection failure, authorization
	// issues, network problems) will result in the stream being terminated with
	// an appropriate RPC status exception.
	//
	// After a successful connection is made, if an error occurs, then the server
	// terminates connection and returns the appropriate RPC status exception.
	StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error
	mustEmbedUnimplementedSqlDataServiceServer()
}

// UnimplementedSqlDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlDataServiceServer struct{}

func (UnimplementedSqlDataServiceServer) StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSqlData not implemented")
}
func (UnimplementedSqlDataServiceServer) mustEmbedUnimplementedSqlDataServiceServer() {}
func (UnimplementedSqlDataServiceServer) testEmbeddedByValue()                        {}

// UnsafeSqlDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlDataServiceServer will
// result in compilation errors.
type UnsafeSqlDataServiceServer interface {
	mustEmbedUnimplementedSqlDataServiceServer()
}

func RegisterSqlDataServiceServer(s grpc.ServiceRegistrar, srv SqlDataServiceServer) {
	// If the following call panics, it indicates UnimplementedSqlDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlDataService_ServiceDesc, srv)
}

func _SqlDataService_StreamSqlData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SqlDataServiceServer).StreamSqlData(&grpc.GenericServerStream[StreamSqlDataRequest, StreamSqlDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataService_StreamSqlDataServer = grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataService_ServiceDesc is the grpc.ServiceDesc for SqlDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.sql.v1beta4.SqlDataService",
	HandlerType: (*SqlDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSqlData",
			Handler:       _SqlDataService_StreamSqlData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/csqlgrpc/sql_data_service.proto",
}

const (
	SqlDataServiceJavaPoC_StreamSqlData_FullMethodName = "/google.cloud.sql.v1beta4.SqlDataServiceJavaPoC/StreamSqlData"
)

// SqlDataServiceJavaPoCClient is the client API for SqlDataServiceJavaPoC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceJavaPoCClient interface {
	// `StreamSqlData` is a temporal endpoint for testing Java PoC
	StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error)
}

type sqlDataServiceJavaPoCClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlDataServiceJavaPoCClient(cc grpc.ClientConnInterface) SqlDataServiceJavaPoCClient {
	return &sqlDataServiceJavaPoCClient{cc}
}

func (c *sqlDataServiceJavaPoCClient) StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SqlDataServiceJavaPoC_ServiceDesc.Streams[0], SqlDataServiceJavaPoC_StreamSqlData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSqlDataRequest, StreamSqlDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataServiceJavaPoC_StreamSqlDataClient = grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataServiceJavaPoCServer is the server API for SqlDataServiceJavaPoC service.
// All implementations must embed UnimplementedSqlDataServiceJavaPoCServer
// for forward compatibility.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceJavaPoCServer interface {
	// `StreamSqlData` is a temporal endpoint for testing Java PoC
	StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error
	mustEmbedUnimplementedSqlDataServiceJavaPoCServer()
}

// UnimplementedSqlDataServiceJavaPoCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlDataServiceJavaPoCServer struct{}

func (UnimplementedSqlDataServiceJavaPoCServer) StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSqlData not implemented")
}
func (UnimplementedSqlDataServiceJavaPoCServer) mustEmbedUnimplementedSqlDataServiceJavaPoCServer() {}
func (UnimplementedSqlDataServiceJavaPoCServer) testEmbeddedByValue()                               {}

// UnsafeSqlDataServiceJavaPoCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlDataServiceJavaPoCServer will
// result in compilation errors.
type UnsafeSqlDataServiceJavaPoCServer interface {
	mustEmbedUnimplementedSqlDataServiceJavaPoCServer()
}

func RegisterSqlDataServiceJavaPoCServer(s grpc.ServiceRegistrar, srv SqlDataServiceJavaPoCServer) {
	// If the following call panics, it indicates UnimplementedSqlDataServiceJavaPoCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlDataServiceJavaPoC_ServiceDesc, srv)
}

func _SqlDataServiceJavaPoC_StreamSqlData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SqlDataServiceJavaPoCServer).StreamSqlData(&grpc.GenericServerStream[StreamSqlDataRequest, StreamSqlDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataServiceJavaPoC_StreamSqlDataServer = grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataServiceJavaPoC_ServiceDesc is the grpc.ServiceDesc for SqlDataServiceJavaPoC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlDataServiceJavaPoC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.sql.v1beta4.SqlDataServiceJavaPoC",
	HandlerType: (*SqlDataServiceJavaPoCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSqlData",
			Handler:       _SqlDataServiceJavaPoC_StreamSqlData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/csqlgrpc/sql_data_service.proto",
}

const (
	SqlDataServiceV3_StreamSqlData_FullMethodName = "/google.cloud.sql.v1beta4.SqlDataServiceV3/StreamSqlData"
)

// SqlDataServiceV3Client is the client API for SqlDataServiceV3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceV3Client interface {
	// `StreamSqlData` is a temporal endpoint for testing Goa V3 PoC
	StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error)
}

type sqlDataServiceV3Client struct {
	cc grpc.ClientConnInterface
}

func NewSqlDataServiceV3Client(cc grpc.ClientConnInterface) SqlDataServiceV3Client {
	return &sqlDataServiceV3Client{cc}
}

func (c *sqlDataServiceV3Client) StreamSqlData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SqlDataServiceV3_ServiceDesc.Streams[0], SqlDataServiceV3_StreamSqlData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSqlDataRequest, StreamSqlDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataServiceV3_StreamSqlDataClient = grpc.BidiStreamingClient[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataServiceV3Server is the server API for SqlDataServiceV3 service.
// All implementations must embed UnimplementedSqlDataServiceV3Server
// for forward compatibility.
//
// Service for streaming data to and from Cloud SQL instances.
type SqlDataServiceV3Server interface {
	// `StreamSqlData` is a temporal endpoint for testing Goa V3 PoC
	StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error
	mustEmbedUnimplementedSqlDataServiceV3Server()
}

// UnimplementedSqlDataServiceV3Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlDataServiceV3Server struct{}

func (UnimplementedSqlDataServiceV3Server) StreamSqlData(grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSqlData not implemented")
}
func (UnimplementedSqlDataServiceV3Server) mustEmbedUnimplementedSqlDataServiceV3Server() {}
func (UnimplementedSqlDataServiceV3Server) testEmbeddedByValue()                          {}

// UnsafeSqlDataServiceV3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlDataServiceV3Server will
// result in compilation errors.
type UnsafeSqlDataServiceV3Server interface {
	mustEmbedUnimplementedSqlDataServiceV3Server()
}

func RegisterSqlDataServiceV3Server(s grpc.ServiceRegistrar, srv SqlDataServiceV3Server) {
	// If the following call panics, it indicates UnimplementedSqlDataServiceV3Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlDataServiceV3_ServiceDesc, srv)
}

func _SqlDataServiceV3_StreamSqlData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SqlDataServiceV3Server).StreamSqlData(&grpc.GenericServerStream[StreamSqlDataRequest, StreamSqlDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlDataServiceV3_StreamSqlDataServer = grpc.BidiStreamingServer[StreamSqlDataRequest, StreamSqlDataResponse]

// SqlDataServiceV3_ServiceDesc is the grpc.ServiceDesc for SqlDataServiceV3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlDataServiceV3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.sql.v1beta4.SqlDataServiceV3",
	HandlerType: (*SqlDataServiceV3Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSqlData",
			Handler:       _SqlDataServiceV3_StreamSqlData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/csqlgrpc/sql_data_service.proto",
}
