// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/sqldata/sql_data_service.proto

package sqldata

import (
	reflect "reflect"
	unsafe "unsafe"

	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error reasons for `StreamSqlData`.
// Typically used with standard error codes, with the error info/reason field
// set to the string representation of the enum value.
type StreamSqlDataErrorReason int32

const (
	// Indicates that the error reason is unknown.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_UNKNOWN StreamSqlDataErrorReason = 0
	// Indicates that the operation is not supported for given instance type.
	// Used with status code `google.rpc.Code.FAILED_PRECONDITION`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE StreamSqlDataErrorReason = 1
	// Indicates that reconnect failed and should not be retried.
	// Used with status code `google.rpc.Code.INTERNAL`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_RECONNECT_FAILED StreamSqlDataErrorReason = 3
	// Indicates that the database client closed its connection normally.
	// Used with status code `google.rpc.Code.CANCELED`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_DB_CLIENT_CLOSED StreamSqlDataErrorReason = 4
	// Indicates that the database server closed its connection normally.
	// Used with status code `google.rpc.Code.CANCELED`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_DB_SERVER_CLOSED StreamSqlDataErrorReason = 5
	// Indicates that the peer sent an ACK message that was not within an
	// acceptable range. Used with the status code
	// `google.rpc.Code.FAILED_PRECONDITION`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_INVALID_ACK StreamSqlDataErrorReason = 6
	// Indicates that the SqlDataService lost its connection to the
	// database instance. This is a retryable error.
	// Used with status code `google.rpc.Code.ABORTED`.
	StreamSqlDataErrorReason_STREAM_SQL_DATA_ERROR_REASON_DISCONNECTED StreamSqlDataErrorReason = 7
)

// Enum value maps for StreamSqlDataErrorReason.
var (
	StreamSqlDataErrorReason_name = map[int32]string{
		0: "STREAM_SQL_DATA_ERROR_REASON_UNKNOWN",
		1: "STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE",
		3: "STREAM_SQL_DATA_ERROR_REASON_RECONNECT_FAILED",
		4: "STREAM_SQL_DATA_ERROR_REASON_DB_CLIENT_CLOSED",
		5: "STREAM_SQL_DATA_ERROR_REASON_DB_SERVER_CLOSED",
		6: "STREAM_SQL_DATA_ERROR_REASON_INVALID_ACK",
		7: "STREAM_SQL_DATA_ERROR_REASON_DISCONNECTED",
	}
	StreamSqlDataErrorReason_value = map[string]int32{
		"STREAM_SQL_DATA_ERROR_REASON_UNKNOWN":                   0,
		"STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE": 1,
		"STREAM_SQL_DATA_ERROR_REASON_RECONNECT_FAILED":          3,
		"STREAM_SQL_DATA_ERROR_REASON_DB_CLIENT_CLOSED":          4,
		"STREAM_SQL_DATA_ERROR_REASON_DB_SERVER_CLOSED":          5,
		"STREAM_SQL_DATA_ERROR_REASON_INVALID_ACK":               6,
		"STREAM_SQL_DATA_ERROR_REASON_DISCONNECTED":              7,
	}
)

func (x StreamSqlDataErrorReason) Enum() *StreamSqlDataErrorReason {
	p := new(StreamSqlDataErrorReason)
	*p = x
	return p
}

func (x StreamSqlDataErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamSqlDataErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_sqldata_sql_data_service_proto_enumTypes[0].Descriptor()
}

func (StreamSqlDataErrorReason) Type() protoreflect.EnumType {
	return &file_internal_sqldata_sql_data_service_proto_enumTypes[0]
}

func (x StreamSqlDataErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The session features. The server must send the supported features in its
// first message to the client.
type SqlDataFeature int32

const (
	// The feature is not specified. This value should not be used.
	SqlDataFeature_SQL_DATA_FEATURE_UNSPECIFIED SqlDataFeature = 0
	// The server supports reconnecting to the session. If this feature is not
	// present, the client should not attempt to reconnect to the session.
	SqlDataFeature_SQL_DATA_FEATURE_RECONNECT SqlDataFeature = 1
)

// Enum value maps for SqlDataFeature.
var (
	SqlDataFeature_name = map[int32]string{
		0: "SQL_DATA_FEATURE_UNSPECIFIED",
		1: "SQL_DATA_FEATURE_RECONNECT",
	}
	SqlDataFeature_value = map[string]int32{
		"SQL_DATA_FEATURE_UNSPECIFIED": 0,
		"SQL_DATA_FEATURE_RECONNECT":   1,
	}
)

func (x SqlDataFeature) Enum() *SqlDataFeature {
	p := new(SqlDataFeature)
	*p = x
	return p
}

func (x SqlDataFeature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SqlDataFeature) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_sqldata_sql_data_service_proto_enumTypes[1].Descriptor()
}

func (SqlDataFeature) Type() protoreflect.EnumType {
	return &file_internal_sqldata_sql_data_service_proto_enumTypes[1]
}

func (x SqlDataFeature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Message sent from the client to `SqlDataService`.
type StreamSqlDataRequest struct {
	state                  protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_LocationId  *string                            `protobuf:"bytes,1,opt,name=location_id,json=locationId"`
	xxx_hidden_MessageType isStreamSqlDataRequest_MessageType `protobuf_oneof:"message_type"`
	xxx_hidden_Ack         *Ack                               `protobuf:"bytes,4,opt,name=ack"`
	xxx_hidden_Message     isStreamSqlDataRequest_Message     `protobuf_oneof:"message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamSqlDataRequest) Reset() {
	*x = StreamSqlDataRequest{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSqlDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSqlDataRequest) ProtoMessage() {}

func (x *StreamSqlDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamSqlDataRequest) GetLocationId() string {
	if x != nil {
		if x.xxx_hidden_LocationId != nil {
			return *x.xxx_hidden_LocationId
		}
		return ""
	}
	return ""
}

func (x *StreamSqlDataRequest) GetConnectionSettings() *ConnectionSettings {
	if x != nil {
		if x, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_ConnectionSettings); ok {
			return x.ConnectionSettings
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetPayload() *ClientPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetAck() *Ack {
	if x != nil {
		return x.xxx_hidden_Ack
	}
	return nil
}

func (x *StreamSqlDataRequest) GetStartSession() *StartSession {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_StartSession); ok {
			return x.StartSession
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetContinueSession() *ContinueSession {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_ContinueSession); ok {
			return x.ContinueSession
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetData() *DataPacket {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) GetTerminateSession() *TerminateSession {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_TerminateSession); ok {
			return x.TerminateSession
		}
	}
	return nil
}

func (x *StreamSqlDataRequest) SetLocationId(v string) {
	x.xxx_hidden_LocationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *StreamSqlDataRequest) SetConnectionSettings(v *ConnectionSettings) {
	if v == nil {
		x.xxx_hidden_MessageType = nil
		return
	}
	x.xxx_hidden_MessageType = &streamSqlDataRequest_ConnectionSettings{v}
}

func (x *StreamSqlDataRequest) SetPayload(v *ClientPayload) {
	if v == nil {
		x.xxx_hidden_MessageType = nil
		return
	}
	x.xxx_hidden_MessageType = &streamSqlDataRequest_Payload{v}
}

func (x *StreamSqlDataRequest) SetAck(v *Ack) {
	x.xxx_hidden_Ack = v
}

func (x *StreamSqlDataRequest) SetStartSession(v *StartSession) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataRequest_StartSession{v}
}

func (x *StreamSqlDataRequest) SetContinueSession(v *ContinueSession) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataRequest_ContinueSession{v}
}

func (x *StreamSqlDataRequest) SetData(v *DataPacket) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataRequest_Data{v}
}

func (x *StreamSqlDataRequest) SetTerminateSession(v *TerminateSession) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataRequest_TerminateSession{v}
}

func (x *StreamSqlDataRequest) HasLocationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamSqlDataRequest) HasMessageType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MessageType != nil
}

func (x *StreamSqlDataRequest) HasConnectionSettings() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_ConnectionSettings)
	return ok
}

func (x *StreamSqlDataRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_Payload)
	return ok
}

func (x *StreamSqlDataRequest) HasAck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ack != nil
}

func (x *StreamSqlDataRequest) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *StreamSqlDataRequest) HasStartSession() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_StartSession)
	return ok
}

func (x *StreamSqlDataRequest) HasContinueSession() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_ContinueSession)
	return ok
}

func (x *StreamSqlDataRequest) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_Data)
	return ok
}

func (x *StreamSqlDataRequest) HasTerminateSession() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_TerminateSession)
	return ok
}

func (x *StreamSqlDataRequest) ClearLocationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LocationId = nil
}

func (x *StreamSqlDataRequest) ClearMessageType() {
	x.xxx_hidden_MessageType = nil
}

func (x *StreamSqlDataRequest) ClearConnectionSettings() {
	if _, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_ConnectionSettings); ok {
		x.xxx_hidden_MessageType = nil
	}
}

func (x *StreamSqlDataRequest) ClearPayload() {
	if _, ok := x.xxx_hidden_MessageType.(*streamSqlDataRequest_Payload); ok {
		x.xxx_hidden_MessageType = nil
	}
}

func (x *StreamSqlDataRequest) ClearAck() {
	x.xxx_hidden_Ack = nil
}

func (x *StreamSqlDataRequest) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *StreamSqlDataRequest) ClearStartSession() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_StartSession); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *StreamSqlDataRequest) ClearContinueSession() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_ContinueSession); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *StreamSqlDataRequest) ClearData() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_Data); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *StreamSqlDataRequest) ClearTerminateSession() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataRequest_TerminateSession); ok {
		x.xxx_hidden_Message = nil
	}
}

const StreamSqlDataRequest_MessageType_not_set_case case_StreamSqlDataRequest_MessageType = 0
const StreamSqlDataRequest_ConnectionSettings_case case_StreamSqlDataRequest_MessageType = 2
const StreamSqlDataRequest_Payload_case case_StreamSqlDataRequest_MessageType = 3

func (x *StreamSqlDataRequest) WhichMessageType() case_StreamSqlDataRequest_MessageType {
	if x == nil {
		return StreamSqlDataRequest_MessageType_not_set_case
	}
	switch x.xxx_hidden_MessageType.(type) {
	case *streamSqlDataRequest_ConnectionSettings:
		return StreamSqlDataRequest_ConnectionSettings_case
	case *streamSqlDataRequest_Payload:
		return StreamSqlDataRequest_Payload_case
	default:
		return StreamSqlDataRequest_MessageType_not_set_case
	}
}

const StreamSqlDataRequest_Message_not_set_case case_StreamSqlDataRequest_Message = 0
const StreamSqlDataRequest_StartSession_case case_StreamSqlDataRequest_Message = 5
const StreamSqlDataRequest_ContinueSession_case case_StreamSqlDataRequest_Message = 6
const StreamSqlDataRequest_Data_case case_StreamSqlDataRequest_Message = 7
const StreamSqlDataRequest_TerminateSession_case case_StreamSqlDataRequest_Message = 8

func (x *StreamSqlDataRequest) WhichMessage() case_StreamSqlDataRequest_Message {
	if x == nil {
		return StreamSqlDataRequest_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *streamSqlDataRequest_StartSession:
		return StreamSqlDataRequest_StartSession_case
	case *streamSqlDataRequest_ContinueSession:
		return StreamSqlDataRequest_ContinueSession_case
	case *streamSqlDataRequest_Data:
		return StreamSqlDataRequest_Data_case
	case *streamSqlDataRequest_TerminateSession:
		return StreamSqlDataRequest_TerminateSession_case
	default:
		return StreamSqlDataRequest_Message_not_set_case
	}
}

type StreamSqlDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Deprecated: Use `StartSession.location_id` or `ContinueSession.location_id`
	// instead. `location_id` is used to route the request to a specific region.
	// Use the same region which was used to create the instance. Use the format
	// `locations/{location}`, for example: `locations/us-central1`.
	LocationId *string
	// Deprecated: Use the `message` oneof instead. The type of message sent
	// within the stream.

	// Fields of oneof xxx_hidden_MessageType:
	// Deprecated: Use `start_session` or `continue_session` instead.
	// Parameters for establishing the connection. MUST be sent as the first
	// message on the stream.
	ConnectionSettings *ConnectionSettings
	// Deprecated: Use `DataPacket` instead.
	// Data to be forwarded to the database.
	Payload *ClientPayload
	// -- end of xxx_hidden_MessageType
	// Acknowledges data received by the client.
	Ack *Ack
	// The message to the server.

	// Fields of oneof xxx_hidden_Message:
	// Starts a new session. When starting a new session, this is the first
	// message the client sends.
	StartSession *StartSession
	// Continues an existing session. When starting a new session, this is the
	// first message the client sends.
	ContinueSession *ContinueSession
	// Database data.
	Data *DataPacket
	// Terminates the session. This closes the connection to the database.
	TerminateSession *TerminateSession
	// -- end of xxx_hidden_Message
}

func (b0 StreamSqlDataRequest_builder) Build() *StreamSqlDataRequest {
	m0 := &StreamSqlDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LocationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_LocationId = b.LocationId
	}
	if b.ConnectionSettings != nil {
		x.xxx_hidden_MessageType = &streamSqlDataRequest_ConnectionSettings{b.ConnectionSettings}
	}
	if b.Payload != nil {
		x.xxx_hidden_MessageType = &streamSqlDataRequest_Payload{b.Payload}
	}
	x.xxx_hidden_Ack = b.Ack
	if b.StartSession != nil {
		x.xxx_hidden_Message = &streamSqlDataRequest_StartSession{b.StartSession}
	}
	if b.ContinueSession != nil {
		x.xxx_hidden_Message = &streamSqlDataRequest_ContinueSession{b.ContinueSession}
	}
	if b.Data != nil {
		x.xxx_hidden_Message = &streamSqlDataRequest_Data{b.Data}
	}
	if b.TerminateSession != nil {
		x.xxx_hidden_Message = &streamSqlDataRequest_TerminateSession{b.TerminateSession}
	}
	return m0
}

type case_StreamSqlDataRequest_MessageType protoreflect.FieldNumber

func (x case_StreamSqlDataRequest_MessageType) String() string {
	md := file_internal_sqldata_sql_data_service_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type case_StreamSqlDataRequest_Message protoreflect.FieldNumber

func (x case_StreamSqlDataRequest_Message) String() string {
	md := file_internal_sqldata_sql_data_service_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStreamSqlDataRequest_MessageType interface {
	isStreamSqlDataRequest_MessageType()
}

type streamSqlDataRequest_ConnectionSettings struct {
	// Deprecated: Use `start_session` or `continue_session` instead.
	// Parameters for establishing the connection. MUST be sent as the first
	// message on the stream.
	ConnectionSettings *ConnectionSettings `protobuf:"bytes,2,opt,name=connection_settings,json=connectionSettings,oneof"`
}

type streamSqlDataRequest_Payload struct {
	// Deprecated: Use `DataPacket` instead.
	// Data to be forwarded to the database.
	Payload *ClientPayload `protobuf:"bytes,3,opt,name=payload,oneof"`
}

func (*streamSqlDataRequest_ConnectionSettings) isStreamSqlDataRequest_MessageType() {}

func (*streamSqlDataRequest_Payload) isStreamSqlDataRequest_MessageType() {}

type isStreamSqlDataRequest_Message interface {
	isStreamSqlDataRequest_Message()
}

type streamSqlDataRequest_StartSession struct {
	// Starts a new session. When starting a new session, this is the first
	// message the client sends.
	StartSession *StartSession `protobuf:"bytes,5,opt,name=start_session,json=startSession,oneof"`
}

type streamSqlDataRequest_ContinueSession struct {
	// Continues an existing session. When starting a new session, this is the
	// first message the client sends.
	ContinueSession *ContinueSession `protobuf:"bytes,6,opt,name=continue_session,json=continueSession,oneof"`
}

type streamSqlDataRequest_Data struct {
	// Database data.
	Data *DataPacket `protobuf:"bytes,7,opt,name=data,oneof"`
}

type streamSqlDataRequest_TerminateSession struct {
	// Terminates the session. This closes the connection to the database.
	TerminateSession *TerminateSession `protobuf:"bytes,8,opt,name=terminate_session,json=terminateSession,oneof"`
}

func (*streamSqlDataRequest_StartSession) isStreamSqlDataRequest_Message() {}

func (*streamSqlDataRequest_ContinueSession) isStreamSqlDataRequest_Message() {}

func (*streamSqlDataRequest_Data) isStreamSqlDataRequest_Message() {}

func (*streamSqlDataRequest_TerminateSession) isStreamSqlDataRequest_Message() {}

// Deprecated:  New schema structure. Initial connection parameters.
//
// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ConnectionSettings struct {
	state             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Target isConnectionSettings_Target `protobuf_oneof:"target"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionSettings) Reset() {
	*x = ConnectionSettings{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSettings) ProtoMessage() {}

func (x *ConnectionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionSettings) GetInstanceId() *InstanceId {
	if x != nil {
		if x, ok := x.xxx_hidden_Target.(*connectionSettings_InstanceId); ok {
			return x.InstanceId
		}
	}
	return nil
}

func (x *ConnectionSettings) SetInstanceId(v *InstanceId) {
	if v == nil {
		x.xxx_hidden_Target = nil
		return
	}
	x.xxx_hidden_Target = &connectionSettings_InstanceId{v}
}

func (x *ConnectionSettings) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *ConnectionSettings) HasInstanceId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Target.(*connectionSettings_InstanceId)
	return ok
}

func (x *ConnectionSettings) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *ConnectionSettings) ClearInstanceId() {
	if _, ok := x.xxx_hidden_Target.(*connectionSettings_InstanceId); ok {
		x.xxx_hidden_Target = nil
	}
}

const ConnectionSettings_Target_not_set_case case_ConnectionSettings_Target = 0
const ConnectionSettings_InstanceId_case case_ConnectionSettings_Target = 1

func (x *ConnectionSettings) WhichTarget() case_ConnectionSettings_Target {
	if x == nil {
		return ConnectionSettings_Target_not_set_case
	}
	switch x.xxx_hidden_Target.(type) {
	case *connectionSettings_InstanceId:
		return ConnectionSettings_InstanceId_case
	default:
		return ConnectionSettings_Target_not_set_case
	}
}

// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ConnectionSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target of the connection.

	// Fields of oneof xxx_hidden_Target:
	// The identifier of the Cloud SQL instance.
	InstanceId *InstanceId
	// -- end of xxx_hidden_Target
}

func (b0 ConnectionSettings_builder) Build() *ConnectionSettings {
	m0 := &ConnectionSettings{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InstanceId != nil {
		x.xxx_hidden_Target = &connectionSettings_InstanceId{b.InstanceId}
	}
	return m0
}

type case_ConnectionSettings_Target protoreflect.FieldNumber

func (x case_ConnectionSettings_Target) String() string {
	md := file_internal_sqldata_sql_data_service_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isConnectionSettings_Target interface {
	isConnectionSettings_Target()
}

type connectionSettings_InstanceId struct {
	// The identifier of the Cloud SQL instance.
	InstanceId *InstanceId `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,oneof"`
}

func (*connectionSettings_InstanceId) isConnectionSettings_Target() {}

// Start a new session. The client must send this as the first message to the
// server to start a new session. The client may immediately send Data messages
// without waiting for a reply from the server.
type StartSession struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocationId  *string                `protobuf:"bytes,1,opt,name=location_id,json=locationId"`
	xxx_hidden_InstanceId  *string                `protobuf:"bytes,2,opt,name=instance_id,json=instanceId"`
	xxx_hidden_SessionId   *string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartSession) Reset() {
	*x = StartSession{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSession) ProtoMessage() {}

func (x *StartSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartSession) GetLocationId() string {
	if x != nil {
		if x.xxx_hidden_LocationId != nil {
			return *x.xxx_hidden_LocationId
		}
		return ""
	}
	return ""
}

func (x *StartSession) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *StartSession) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *StartSession) SetLocationId(v string) {
	x.xxx_hidden_LocationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *StartSession) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StartSession) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StartSession) HasLocationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartSession) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StartSession) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StartSession) ClearLocationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LocationId = nil
}

func (x *StartSession) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstanceId = nil
}

func (x *StartSession) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SessionId = nil
}

type StartSession_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// `location_id` is used to route the
	// request to a specific region. Use the same region which was used to create
	// the instance. Use the format `locations/{location}`, for example:
	// `locations/us-central1`.
	LocationId *string
	// The Cloud SQL instance resource name, for example:
	// projects/example-project/instances/example-instance
	InstanceId *string
	// The session id, chosen by the client. This should be an unguessable string.
	// If the client does not intend to reconnect to this session, the client may
	// leave session_id unset.
	SessionId *string
}

func (b0 StartSession_builder) Build() *StartSession {
	m0 := &StartSession{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LocationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_LocationId = b.LocationId
	}
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SessionId = b.SessionId
	}
	return m0
}

// Reconnects to an existing session. The client must send this as the first
// message to the server to reconnect to an existing session. The client may
// immediately send Data messages without waiting for a reply from the server.
type ContinueSession struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocationId  *string                `protobuf:"bytes,1,opt,name=location_id,json=locationId"`
	xxx_hidden_InstanceId  *string                `protobuf:"bytes,2,opt,name=instance_id,json=instanceId"`
	xxx_hidden_SessionId   *string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContinueSession) Reset() {
	*x = ContinueSession{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueSession) ProtoMessage() {}

func (x *ContinueSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContinueSession) GetLocationId() string {
	if x != nil {
		if x.xxx_hidden_LocationId != nil {
			return *x.xxx_hidden_LocationId
		}
		return ""
	}
	return ""
}

func (x *ContinueSession) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *ContinueSession) GetSessionId() string {
	if x != nil {
		if x.xxx_hidden_SessionId != nil {
			return *x.xxx_hidden_SessionId
		}
		return ""
	}
	return ""
}

func (x *ContinueSession) SetLocationId(v string) {
	x.xxx_hidden_LocationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ContinueSession) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ContinueSession) SetSessionId(v string) {
	x.xxx_hidden_SessionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ContinueSession) HasLocationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContinueSession) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContinueSession) HasSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ContinueSession) ClearLocationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LocationId = nil
}

func (x *ContinueSession) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstanceId = nil
}

func (x *ContinueSession) ClearSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SessionId = nil
}

type ContinueSession_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// `location_id` is used to route the
	// request to a specific region. Use the same region which was used to create
	// the instance. Use the format `locations/{location}`, for example:
	// `locations/us-central1`.
	LocationId *string
	// The Cloud SQL instance resource name, for example:
	// projects/example-project/instances/example-instance
	InstanceId *string
	// The id of the session to reconnect.
	SessionId *string
}

func (b0 ContinueSession_builder) Build() *ContinueSession {
	m0 := &ContinueSession{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LocationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_LocationId = b.LocationId
	}
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.SessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SessionId = b.SessionId
	}
	return m0
}

// Deprecated:  New schema structure. The identifier of the Cloud SQL instance.
//
// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type InstanceId struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance    *string                `protobuf:"bytes,1,opt,name=instance"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InstanceId) Reset() {
	*x = InstanceId{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceId) ProtoMessage() {}

func (x *InstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceId) GetInstance() string {
	if x != nil {
		if x.xxx_hidden_Instance != nil {
			return *x.xxx_hidden_Instance
		}
		return ""
	}
	return ""
}

func (x *InstanceId) SetInstance(v string) {
	x.xxx_hidden_Instance = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InstanceId) HasInstance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InstanceId) ClearInstance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Instance = nil
}

// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type InstanceId_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Full resource name of the Cloud SQL instance, in the form:
	// `projects/{project}/instances/{instance}`, for example:
	// `projects/foo-project/instances/bar-instance`.
	Instance *string
}

func (b0 InstanceId_builder) Build() *InstanceId {
	m0 := &InstanceId{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Instance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Instance = b.Instance
	}
	return m0
}

// Deprecated:  New schema structure. Wrapper for data being sent to the
// database.
//
// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ClientPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientPayload) Reset() {
	*x = ClientPayload{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPayload) ProtoMessage() {}

func (x *ClientPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClientPayload) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ClientPayload) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ClientPayload) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ClientPayload) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ClientPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Raw data to be sent to the database. See the documentation for
	// `StreamSqlData` for details on the expected wire format.
	Data []byte
}

func (b0 ClientPayload_builder) Build() *ClientPayload {
	m0 := &ClientPayload{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

// Message sent from SqlDataService back to the client.
type StreamSqlDataResponse struct {
	state              protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Type    isStreamSqlDataResponse_Type    `protobuf_oneof:"type"`
	xxx_hidden_Ack     *Ack                            `protobuf:"bytes,2,opt,name=ack"`
	xxx_hidden_Message isStreamSqlDataResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamSqlDataResponse) Reset() {
	*x = StreamSqlDataResponse{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSqlDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSqlDataResponse) ProtoMessage() {}

func (x *StreamSqlDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamSqlDataResponse) GetPayload() *ServerPayload {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*streamSqlDataResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *StreamSqlDataResponse) GetAck() *Ack {
	if x != nil {
		return x.xxx_hidden_Ack
	}
	return nil
}

func (x *StreamSqlDataResponse) GetSessionMetadata() *SessionMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_SessionMetadata); ok {
			return x.SessionMetadata
		}
	}
	return nil
}

func (x *StreamSqlDataResponse) GetData() *DataPacket {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *StreamSqlDataResponse) GetTerminateSession() *TerminateSession {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_TerminateSession); ok {
			return x.TerminateSession
		}
	}
	return nil
}

func (x *StreamSqlDataResponse) SetPayload(v *ServerPayload) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &streamSqlDataResponse_Payload{v}
}

func (x *StreamSqlDataResponse) SetAck(v *Ack) {
	x.xxx_hidden_Ack = v
}

func (x *StreamSqlDataResponse) SetSessionMetadata(v *SessionMetadata) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataResponse_SessionMetadata{v}
}

func (x *StreamSqlDataResponse) SetData(v *DataPacket) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataResponse_Data{v}
}

func (x *StreamSqlDataResponse) SetTerminateSession(v *TerminateSession) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &streamSqlDataResponse_TerminateSession{v}
}

func (x *StreamSqlDataResponse) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *StreamSqlDataResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*streamSqlDataResponse_Payload)
	return ok
}

func (x *StreamSqlDataResponse) HasAck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ack != nil
}

func (x *StreamSqlDataResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *StreamSqlDataResponse) HasSessionMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_SessionMetadata)
	return ok
}

func (x *StreamSqlDataResponse) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_Data)
	return ok
}

func (x *StreamSqlDataResponse) HasTerminateSession() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_TerminateSession)
	return ok
}

func (x *StreamSqlDataResponse) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *StreamSqlDataResponse) ClearPayload() {
	if _, ok := x.xxx_hidden_Type.(*streamSqlDataResponse_Payload); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *StreamSqlDataResponse) ClearAck() {
	x.xxx_hidden_Ack = nil
}

func (x *StreamSqlDataResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *StreamSqlDataResponse) ClearSessionMetadata() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_SessionMetadata); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *StreamSqlDataResponse) ClearData() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_Data); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *StreamSqlDataResponse) ClearTerminateSession() {
	if _, ok := x.xxx_hidden_Message.(*streamSqlDataResponse_TerminateSession); ok {
		x.xxx_hidden_Message = nil
	}
}

const StreamSqlDataResponse_Type_not_set_case case_StreamSqlDataResponse_Type = 0
const StreamSqlDataResponse_Payload_case case_StreamSqlDataResponse_Type = 1

func (x *StreamSqlDataResponse) WhichType() case_StreamSqlDataResponse_Type {
	if x == nil {
		return StreamSqlDataResponse_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *streamSqlDataResponse_Payload:
		return StreamSqlDataResponse_Payload_case
	default:
		return StreamSqlDataResponse_Type_not_set_case
	}
}

const StreamSqlDataResponse_Message_not_set_case case_StreamSqlDataResponse_Message = 0
const StreamSqlDataResponse_SessionMetadata_case case_StreamSqlDataResponse_Message = 3
const StreamSqlDataResponse_Data_case case_StreamSqlDataResponse_Message = 4
const StreamSqlDataResponse_TerminateSession_case case_StreamSqlDataResponse_Message = 5

func (x *StreamSqlDataResponse) WhichMessage() case_StreamSqlDataResponse_Message {
	if x == nil {
		return StreamSqlDataResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *streamSqlDataResponse_SessionMetadata:
		return StreamSqlDataResponse_SessionMetadata_case
	case *streamSqlDataResponse_Data:
		return StreamSqlDataResponse_Data_case
	case *streamSqlDataResponse_TerminateSession:
		return StreamSqlDataResponse_TerminateSession_case
	default:
		return StreamSqlDataResponse_Message_not_set_case
	}
}

type StreamSqlDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Deprecated:  New schema structure. The type of the message received from
	// `SqlDataService`.

	// Fields of oneof xxx_hidden_Type:
	// Raw data received from the database.
	Payload *ServerPayload
	// -- end of xxx_hidden_Type
	// Acknowledges data received by the server.
	Ack *Ack
	// A message from the server to the client.

	// Fields of oneof xxx_hidden_Message:
	// The first message from the server to the client, containing metadata
	// about this session.
	SessionMetadata *SessionMetadata
	// Data from the database.
	Data *DataPacket
	// Terminates the session. This indicates that the database connection
	// is closed. When the client receives this message, it should not
	// attempt to reconnect.
	TerminateSession *TerminateSession
	// -- end of xxx_hidden_Message
}

func (b0 StreamSqlDataResponse_builder) Build() *StreamSqlDataResponse {
	m0 := &StreamSqlDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Payload != nil {
		x.xxx_hidden_Type = &streamSqlDataResponse_Payload{b.Payload}
	}
	x.xxx_hidden_Ack = b.Ack
	if b.SessionMetadata != nil {
		x.xxx_hidden_Message = &streamSqlDataResponse_SessionMetadata{b.SessionMetadata}
	}
	if b.Data != nil {
		x.xxx_hidden_Message = &streamSqlDataResponse_Data{b.Data}
	}
	if b.TerminateSession != nil {
		x.xxx_hidden_Message = &streamSqlDataResponse_TerminateSession{b.TerminateSession}
	}
	return m0
}

type case_StreamSqlDataResponse_Type protoreflect.FieldNumber

func (x case_StreamSqlDataResponse_Type) String() string {
	md := file_internal_sqldata_sql_data_service_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type case_StreamSqlDataResponse_Message protoreflect.FieldNumber

func (x case_StreamSqlDataResponse_Message) String() string {
	md := file_internal_sqldata_sql_data_service_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStreamSqlDataResponse_Type interface {
	isStreamSqlDataResponse_Type()
}

type streamSqlDataResponse_Payload struct {
	// Raw data received from the database.
	Payload *ServerPayload `protobuf:"bytes,1,opt,name=payload,oneof"`
}

func (*streamSqlDataResponse_Payload) isStreamSqlDataResponse_Type() {}

type isStreamSqlDataResponse_Message interface {
	isStreamSqlDataResponse_Message()
}

type streamSqlDataResponse_SessionMetadata struct {
	// The first message from the server to the client, containing metadata
	// about this session.
	SessionMetadata *SessionMetadata `protobuf:"bytes,3,opt,name=session_metadata,json=sessionMetadata,oneof"`
}

type streamSqlDataResponse_Data struct {
	// Data from the database.
	Data *DataPacket `protobuf:"bytes,4,opt,name=data,oneof"`
}

type streamSqlDataResponse_TerminateSession struct {
	// Terminates the session. This indicates that the database connection
	// is closed. When the client receives this message, it should not
	// attempt to reconnect.
	TerminateSession *TerminateSession `protobuf:"bytes,5,opt,name=terminate_session,json=terminateSession,oneof"`
}

func (*streamSqlDataResponse_SessionMetadata) isStreamSqlDataResponse_Message() {}

func (*streamSqlDataResponse_Data) isStreamSqlDataResponse_Message() {}

func (*streamSqlDataResponse_TerminateSession) isStreamSqlDataResponse_Message() {}

// Deprecated:  New schema structure. Wrapper for data being received from the
// database.
//
// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ServerPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServerPayload) Reset() {
	*x = ServerPayload{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPayload) ProtoMessage() {}

func (x *ServerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServerPayload) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ServerPayload) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServerPayload) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServerPayload) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

// Deprecated: Marked as deprecated in internal/sqldata/sql_data_service.proto.
type ServerPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Raw data received from the database. See the documentation for
	// `StreamSqlData` for details on the expected wire format.
	Data []byte
}

func (b0 ServerPayload_builder) Build() *ServerPayload {
	m0 := &ServerPayload{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

// Metadata from the server to the client about the session. The server will
// always send this as the first message
type SessionMetadata struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SupportedFeatures []SqlDataFeature       `protobuf:"varint,1,rep,packed,name=supported_features,json=supportedFeatures,enum=google.cloud.sql.v1beta4.SqlDataFeature"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SessionMetadata) Reset() {
	*x = SessionMetadata{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetadata) ProtoMessage() {}

func (x *SessionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionMetadata) GetSupportedFeatures() []SqlDataFeature {
	if x != nil {
		return x.xxx_hidden_SupportedFeatures
	}
	return nil
}

func (x *SessionMetadata) SetSupportedFeatures(v []SqlDataFeature) {
	x.xxx_hidden_SupportedFeatures = v
}

type SessionMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The features supported by the server for this session. This field is used
	// by the client to determine which features are available on the server.
	// The features supported by the server for this session.
	SupportedFeatures []SqlDataFeature
}

func (b0 SessionMetadata_builder) Build() *SessionMetadata {
	m0 := &SessionMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SupportedFeatures = b.SupportedFeatures
	return m0
}

// Contains data being sent or received by the database.
type DataPacket struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FirstByteOffset int64                  `protobuf:"varint,1,opt,name=first_byte_offset,json=firstByteOffset"`
	xxx_hidden_Data            []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataPacket) GetFirstByteOffset() int64 {
	if x != nil {
		return x.xxx_hidden_FirstByteOffset
	}
	return 0
}

func (x *DataPacket) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DataPacket) SetFirstByteOffset(v int64) {
	x.xxx_hidden_FirstByteOffset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DataPacket) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DataPacket) HasFirstByteOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataPacket) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataPacket) ClearFirstByteOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FirstByteOffset = 0
}

func (x *DataPacket) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type DataPacket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The absolute byte offset of the first byte in this payload.
	// 0 for new connections or resumed connections that hasn't acked any bytes
	// from server. Non-zero for resumed connections
	FirstByteOffset *int64
	// Raw data being sent or received by the database.
	Data []byte
}

func (b0 DataPacket_builder) Build() *DataPacket {
	m0 := &DataPacket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FirstByteOffset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FirstByteOffset = *b.FirstByteOffset
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

// Acknowledges data received by the client or server.
type Ack struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReceivedOffset int64                  `protobuf:"varint,1,opt,name=received_offset,json=receivedOffset"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ack) GetReceivedOffset() int64 {
	if x != nil {
		return x.xxx_hidden_ReceivedOffset
	}
	return 0
}

func (x *Ack) SetReceivedOffset(v int64) {
	x.xxx_hidden_ReceivedOffset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Ack) HasReceivedOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ack) ClearReceivedOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ReceivedOffset = 0
}

type Ack_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The absolute number of bytes processed in the session.
	ReceivedOffset *int64
}

func (b0 Ack_builder) Build() *Ack {
	m0 := &Ack{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ReceivedOffset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ReceivedOffset = *b.ReceivedOffset
	}
	return m0
}

// Indicates that the session is permanently ended.
type TerminateSession struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status *status.Status         `protobuf:"bytes,1,opt,name=status"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TerminateSession) Reset() {
	*x = TerminateSession{}
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSession) ProtoMessage() {}

func (x *TerminateSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sqldata_sql_data_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminateSession) GetStatus() *status.Status {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *TerminateSession) SetStatus(v *status.Status) {
	x.xxx_hidden_Status = v
}

func (x *TerminateSession) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *TerminateSession) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type TerminateSession_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The session termination status.
	Status *status.Status
}

func (b0 TerminateSession_builder) Build() *TerminateSession {
	m0 := &TerminateSession{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

var File_internal_sqldata_sql_data_service_proto protoreflect.FileDescriptor

const file_internal_sqldata_sql_data_service_proto_rawDesc = "" +
	"\n" +
	"'internal/sqldata/sql_data_service.proto\x12\x18google.cloud.sql.v1beta4\x1a\x17google/rpc/status.proto\"\xe7\x04\n" +
	"\x14StreamSqlDataRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12_\n" +
	"\x13connection_settings\x18\x02 \x01(\v2,.google.cloud.sql.v1beta4.ConnectionSettingsH\x00R\x12connectionSettings\x12C\n" +
	"\apayload\x18\x03 \x01(\v2'.google.cloud.sql.v1beta4.ClientPayloadH\x00R\apayload\x12/\n" +
	"\x03ack\x18\x04 \x01(\v2\x1d.google.cloud.sql.v1beta4.AckR\x03ack\x12M\n" +
	"\rstart_session\x18\x05 \x01(\v2&.google.cloud.sql.v1beta4.StartSessionH\x01R\fstartSession\x12V\n" +
	"\x10continue_session\x18\x06 \x01(\v2).google.cloud.sql.v1beta4.ContinueSessionH\x01R\x0fcontinueSession\x12:\n" +
	"\x04data\x18\a \x01(\v2$.google.cloud.sql.v1beta4.DataPacketH\x01R\x04data\x12Y\n" +
	"\x11terminate_session\x18\b \x01(\v2*.google.cloud.sql.v1beta4.TerminateSessionH\x01R\x10terminateSessionB\x0e\n" +
	"\fmessage_typeB\t\n" +
	"\amessage\"k\n" +
	"\x12ConnectionSettings\x12G\n" +
	"\vinstance_id\x18\x01 \x01(\v2$.google.cloud.sql.v1beta4.InstanceIdH\x00R\n" +
	"instanceId:\x02\x18\x01B\b\n" +
	"\x06target\"o\n" +
	"\fStartSession\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"r\n" +
	"\x0fContinueSession\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\",\n" +
	"\n" +
	"InstanceId\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance:\x02\x18\x01\"'\n" +
	"\rClientPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data:\x02\x18\x01\"\x8f\x03\n" +
	"\x15StreamSqlDataResponse\x12C\n" +
	"\apayload\x18\x01 \x01(\v2'.google.cloud.sql.v1beta4.ServerPayloadH\x00R\apayload\x12/\n" +
	"\x03ack\x18\x02 \x01(\v2\x1d.google.cloud.sql.v1beta4.AckR\x03ack\x12V\n" +
	"\x10session_metadata\x18\x03 \x01(\v2).google.cloud.sql.v1beta4.SessionMetadataH\x01R\x0fsessionMetadata\x12:\n" +
	"\x04data\x18\x04 \x01(\v2$.google.cloud.sql.v1beta4.DataPacketH\x01R\x04data\x12Y\n" +
	"\x11terminate_session\x18\x05 \x01(\v2*.google.cloud.sql.v1beta4.TerminateSessionH\x01R\x10terminateSessionB\x06\n" +
	"\x04typeB\t\n" +
	"\amessage\"'\n" +
	"\rServerPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data:\x02\x18\x01\"j\n" +
	"\x0fSessionMetadata\x12W\n" +
	"\x12supported_features\x18\x01 \x03(\x0e2(.google.cloud.sql.v1beta4.SqlDataFeatureR\x11supportedFeatures\"L\n" +
	"\n" +
	"DataPacket\x12*\n" +
	"\x11first_byte_offset\x18\x01 \x01(\x03R\x0ffirstByteOffset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\".\n" +
	"\x03Ack\x12'\n" +
	"\x0freceived_offset\x18\x01 \x01(\x03R\x0ereceivedOffset\">\n" +
	"\x10TerminateSession\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status*\xf6\x02\n" +
	"\x18StreamSqlDataErrorReason\x12(\n" +
	"$STREAM_SQL_DATA_ERROR_REASON_UNKNOWN\x10\x00\x12:\n" +
	"6STREAM_SQL_DATA_ERROR_REASON_UNSUPPORTED_INSTANCE_TYPE\x10\x01\x121\n" +
	"-STREAM_SQL_DATA_ERROR_REASON_RECONNECT_FAILED\x10\x03\x121\n" +
	"-STREAM_SQL_DATA_ERROR_REASON_DB_CLIENT_CLOSED\x10\x04\x121\n" +
	"-STREAM_SQL_DATA_ERROR_REASON_DB_SERVER_CLOSED\x10\x05\x12,\n" +
	"(STREAM_SQL_DATA_ERROR_REASON_INVALID_ACK\x10\x06\x12-\n" +
	")STREAM_SQL_DATA_ERROR_REASON_DISCONNECTED\x10\a*R\n" +
	"\x0eSqlDataFeature\x12 \n" +
	"\x1cSQL_DATA_FEATURE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSQL_DATA_FEATURE_RECONNECT\x10\x012\x88\x01\n" +
	"\x0eSqlDataService\x12v\n" +
	"\rStreamSqlData\x12..google.cloud.sql.v1beta4.StreamSqlDataRequest\x1a/.google.cloud.sql.v1beta4.StreamSqlDataResponse\"\x00(\x010\x01BC\n" +
	"\x1ccom.google.cloud.sql.v1beta4B\x11CloudSqlDataProtoZ\x10internal/sqldatab\beditionsp\xe9\a"

var file_internal_sqldata_sql_data_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_sqldata_sql_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_sqldata_sql_data_service_proto_goTypes = []any{
	(StreamSqlDataErrorReason)(0), // 0: google.cloud.sql.v1beta4.StreamSqlDataErrorReason
	(SqlDataFeature)(0),           // 1: google.cloud.sql.v1beta4.SqlDataFeature
	(*StreamSqlDataRequest)(nil),  // 2: google.cloud.sql.v1beta4.StreamSqlDataRequest
	(*ConnectionSettings)(nil),    // 3: google.cloud.sql.v1beta4.ConnectionSettings
	(*StartSession)(nil),          // 4: google.cloud.sql.v1beta4.StartSession
	(*ContinueSession)(nil),       // 5: google.cloud.sql.v1beta4.ContinueSession
	(*InstanceId)(nil),            // 6: google.cloud.sql.v1beta4.InstanceId
	(*ClientPayload)(nil),         // 7: google.cloud.sql.v1beta4.ClientPayload
	(*StreamSqlDataResponse)(nil), // 8: google.cloud.sql.v1beta4.StreamSqlDataResponse
	(*ServerPayload)(nil),         // 9: google.cloud.sql.v1beta4.ServerPayload
	(*SessionMetadata)(nil),       // 10: google.cloud.sql.v1beta4.SessionMetadata
	(*DataPacket)(nil),            // 11: google.cloud.sql.v1beta4.DataPacket
	(*Ack)(nil),                   // 12: google.cloud.sql.v1beta4.Ack
	(*TerminateSession)(nil),      // 13: google.cloud.sql.v1beta4.TerminateSession
	(*status.Status)(nil),         // 14: google.rpc.Status
}
var file_internal_sqldata_sql_data_service_proto_depIdxs = []int32{
	3,  // 0: google.cloud.sql.v1beta4.StreamSqlDataRequest.connection_settings:type_name -> google.cloud.sql.v1beta4.ConnectionSettings
	7,  // 1: google.cloud.sql.v1beta4.StreamSqlDataRequest.payload:type_name -> google.cloud.sql.v1beta4.ClientPayload
	12, // 2: google.cloud.sql.v1beta4.StreamSqlDataRequest.ack:type_name -> google.cloud.sql.v1beta4.Ack
	4,  // 3: google.cloud.sql.v1beta4.StreamSqlDataRequest.start_session:type_name -> google.cloud.sql.v1beta4.StartSession
	5,  // 4: google.cloud.sql.v1beta4.StreamSqlDataRequest.continue_session:type_name -> google.cloud.sql.v1beta4.ContinueSession
	11, // 5: google.cloud.sql.v1beta4.StreamSqlDataRequest.data:type_name -> google.cloud.sql.v1beta4.DataPacket
	13, // 6: google.cloud.sql.v1beta4.StreamSqlDataRequest.terminate_session:type_name -> google.cloud.sql.v1beta4.TerminateSession
	6,  // 7: google.cloud.sql.v1beta4.ConnectionSettings.instance_id:type_name -> google.cloud.sql.v1beta4.InstanceId
	9,  // 8: google.cloud.sql.v1beta4.StreamSqlDataResponse.payload:type_name -> google.cloud.sql.v1beta4.ServerPayload
	12, // 9: google.cloud.sql.v1beta4.StreamSqlDataResponse.ack:type_name -> google.cloud.sql.v1beta4.Ack
	10, // 10: google.cloud.sql.v1beta4.StreamSqlDataResponse.session_metadata:type_name -> google.cloud.sql.v1beta4.SessionMetadata
	11, // 11: google.cloud.sql.v1beta4.StreamSqlDataResponse.data:type_name -> google.cloud.sql.v1beta4.DataPacket
	13, // 12: google.cloud.sql.v1beta4.StreamSqlDataResponse.terminate_session:type_name -> google.cloud.sql.v1beta4.TerminateSession
	1,  // 13: google.cloud.sql.v1beta4.SessionMetadata.supported_features:type_name -> google.cloud.sql.v1beta4.SqlDataFeature
	14, // 14: google.cloud.sql.v1beta4.TerminateSession.status:type_name -> google.rpc.Status
	2,  // 15: google.cloud.sql.v1beta4.SqlDataService.StreamSqlData:input_type -> google.cloud.sql.v1beta4.StreamSqlDataRequest
	8,  // 16: google.cloud.sql.v1beta4.SqlDataService.StreamSqlData:output_type -> google.cloud.sql.v1beta4.StreamSqlDataResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_sqldata_sql_data_service_proto_init() }
func file_internal_sqldata_sql_data_service_proto_init() {
	if File_internal_sqldata_sql_data_service_proto != nil {
		return
	}
	file_internal_sqldata_sql_data_service_proto_msgTypes[0].OneofWrappers = []any{
		(*streamSqlDataRequest_ConnectionSettings)(nil),
		(*streamSqlDataRequest_Payload)(nil),
		(*streamSqlDataRequest_StartSession)(nil),
		(*streamSqlDataRequest_ContinueSession)(nil),
		(*streamSqlDataRequest_Data)(nil),
		(*streamSqlDataRequest_TerminateSession)(nil),
	}
	file_internal_sqldata_sql_data_service_proto_msgTypes[1].OneofWrappers = []any{
		(*connectionSettings_InstanceId)(nil),
	}
	file_internal_sqldata_sql_data_service_proto_msgTypes[6].OneofWrappers = []any{
		(*streamSqlDataResponse_Payload)(nil),
		(*streamSqlDataResponse_SessionMetadata)(nil),
		(*streamSqlDataResponse_Data)(nil),
		(*streamSqlDataResponse_TerminateSession)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sqldata_sql_data_service_proto_rawDesc), len(file_internal_sqldata_sql_data_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sqldata_sql_data_service_proto_goTypes,
		DependencyIndexes: file_internal_sqldata_sql_data_service_proto_depIdxs,
		EnumInfos:         file_internal_sqldata_sql_data_service_proto_enumTypes,
		MessageInfos:      file_internal_sqldata_sql_data_service_proto_msgTypes,
	}.Build()
	File_internal_sqldata_sql_data_service_proto = out.File
	file_internal_sqldata_sql_data_service_proto_goTypes = nil
	file_internal_sqldata_sql_data_service_proto_depIdxs = nil
}
