// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12

package connectorspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataExchangeRequest_ClientProtocolType int32

const (
	// Client Protocol Type is unspecified, TCP is used as default
	MetadataExchangeRequest_CLIENT_PROTOCOL_TYPE_UNSPECIFIED MetadataExchangeRequest_ClientProtocolType = 0
	// TCP socket connection
	MetadataExchangeRequest_TCP MetadataExchangeRequest_ClientProtocolType = 1
	// Unix Domain Socket (UDS) connectionMetadataExchangeRequest
	MetadataExchangeRequest_UDS MetadataExchangeRequest_ClientProtocolType = 2
)

// Enum value maps for MetadataExchangeRequest_ClientProtocolType.
var (
	MetadataExchangeRequest_ClientProtocolType_name = map[int32]string{
		0: "CLIENT_PROTOCOL_TYPE_UNSPECIFIED",
		1: "TCP",
		2: "UDS",
	}
	MetadataExchangeRequest_ClientProtocolType_value = map[string]int32{
		"CLIENT_PROTOCOL_TYPE_UNSPECIFIED": 0,
		"TCP":                              1,
		"UDS":                              2,
	}
)

func (x MetadataExchangeRequest_ClientProtocolType) Enum() *MetadataExchangeRequest_ClientProtocolType {
	p := new(MetadataExchangeRequest_ClientProtocolType)
	*p = x
	return p
}

func (x MetadataExchangeRequest_ClientProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataExchangeRequest_ClientProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes[0].Descriptor()
}

func (MetadataExchangeRequest_ClientProtocolType) Type() protoreflect.EnumType {
	return &file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes[0]
}

func (x MetadataExchangeRequest_ClientProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataExchangeRequest_ClientProtocolType.Descriptor instead.
func (MetadataExchangeRequest_ClientProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescGZIP(), []int{0, 0}
}

type MetadataExchangeResponse_ResponseCode int32

const (
	// Unknown response code
	MetadataExchangeResponse_RESPONSE_CODE_UNSPECIFIED MetadataExchangeResponse_ResponseCode = 0
	// Success
	MetadataExchangeResponse_OK MetadataExchangeResponse_ResponseCode = 1
	// Failure
	MetadataExchangeResponse_ERROR MetadataExchangeResponse_ResponseCode = 2
)

// Enum value maps for MetadataExchangeResponse_ResponseCode.
var (
	MetadataExchangeResponse_ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNSPECIFIED",
		1: "OK",
		2: "ERROR",
	}
	MetadataExchangeResponse_ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED": 0,
		"OK":                        1,
		"ERROR":                     2,
	}
)

func (x MetadataExchangeResponse_ResponseCode) Enum() *MetadataExchangeResponse_ResponseCode {
	p := new(MetadataExchangeResponse_ResponseCode)
	*p = x
	return p
}

func (x MetadataExchangeResponse_ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataExchangeResponse_ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes[1].Descriptor()
}

func (MetadataExchangeResponse_ResponseCode) Type() protoreflect.EnumType {
	return &file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes[1]
}

func (x MetadataExchangeResponse_ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataExchangeResponse_ResponseCode.Descriptor instead.
func (MetadataExchangeResponse_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescGZIP(), []int{1, 0}
}

type MetadataExchangeRequest struct {
	state              protoimpl.MessageState                     `protogen:"open.v1"`
	UserAgent          string                                     `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // e.g. cloud-sql-proxy/2.15.2,
	ClientProtocolType MetadataExchangeRequest_ClientProtocolType `protobuf:"varint,2,opt,name=client_protocol_type,json=clientProtocolType,proto3,enum=google.cloud.sql.v1beta4.MetadataExchangeRequest_ClientProtocolType" json:"client_protocol_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataExchangeRequest) Reset() {
	*x = MetadataExchangeRequest{}
	mi := &file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExchangeRequest) ProtoMessage() {}

func (x *MetadataExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExchangeRequest.ProtoReflect.Descriptor instead.
func (*MetadataExchangeRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataExchangeRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *MetadataExchangeRequest) GetClientProtocolType() MetadataExchangeRequest_ClientProtocolType {
	if x != nil {
		return x.ClientProtocolType
	}
	return MetadataExchangeRequest_CLIENT_PROTOCOL_TYPE_UNSPECIFIED
}

type MetadataExchangeResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	ResponseCode  MetadataExchangeResponse_ResponseCode `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=google.cloud.sql.v1beta4.MetadataExchangeResponse_ResponseCode" json:"response_code,omitempty"`
	Error         string                                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataExchangeResponse) Reset() {
	*x = MetadataExchangeResponse{}
	mi := &file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExchangeResponse) ProtoMessage() {}

func (x *MetadataExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExchangeResponse.ProtoReflect.Descriptor instead.
func (*MetadataExchangeResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataExchangeResponse) GetResponseCode() MetadataExchangeResponse_ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return MetadataExchangeResponse_RESPONSE_CODE_UNSPECIFIED
}

func (x *MetadataExchangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_google_cloud_sql_v1beta4_metadata_exchange_proto protoreflect.FileDescriptor

const file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDesc = "" +
	"\n" +
	"0google/cloud/sql/v1beta4/metadata_exchange.proto\x12\x18google.cloud.sql.v1beta4\x1a\x1fgoogle/api/field_behavior.proto\"\x83\x02\n" +
	"\x17MetadataExchangeRequest\x12\"\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tB\x03\xe0A\x01R\tuserAgent\x12v\n" +
	"\x14client_protocol_type\x18\x02 \x01(\x0e2D.google.cloud.sql.v1beta4.MetadataExchangeRequest.ClientProtocolTypeR\x12clientProtocolType\"L\n" +
	"\x12ClientProtocolType\x12$\n" +
	" CLIENT_PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDS\x10\x02\"\xdd\x01\n" +
	"\x18MetadataExchangeResponse\x12d\n" +
	"\rresponse_code\x18\x01 \x01(\x0e2?.google.cloud.sql.v1beta4.MetadataExchangeResponse.ResponseCodeR\fresponseCode\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tB\x03\xe0A\x01R\x05error\"@\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02B'Z%google/cloud/sql/v1beta4/connectorspbb\x06proto3"

var (
	file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescOnce sync.Once
	file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescData []byte
)

func file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescGZIP() []byte {
	file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescOnce.Do(func() {
		file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDesc), len(file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDesc)))
	})
	return file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDescData
}

var file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_cloud_sql_v1beta4_metadata_exchange_proto_goTypes = []any{
	(MetadataExchangeRequest_ClientProtocolType)(0), // 0: google.cloud.sql.v1beta4.MetadataExchangeRequest.ClientProtocolType
	(MetadataExchangeResponse_ResponseCode)(0),      // 1: google.cloud.sql.v1beta4.MetadataExchangeResponse.ResponseCode
	(*MetadataExchangeRequest)(nil),                 // 2: google.cloud.sql.v1beta4.MetadataExchangeRequest
	(*MetadataExchangeResponse)(nil),                // 3: google.cloud.sql.v1beta4.MetadataExchangeResponse
}
var file_google_cloud_sql_v1beta4_metadata_exchange_proto_depIdxs = []int32{
	0, // 0: google.cloud.sql.v1beta4.MetadataExchangeRequest.client_protocol_type:type_name -> google.cloud.sql.v1beta4.MetadataExchangeRequest.ClientProtocolType
	1, // 1: google.cloud.sql.v1beta4.MetadataExchangeResponse.response_code:type_name -> google.cloud.sql.v1beta4.MetadataExchangeResponse.ResponseCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_google_cloud_sql_v1beta4_metadata_exchange_proto_init() }
func file_google_cloud_sql_v1beta4_metadata_exchange_proto_init() {
	if File_google_cloud_sql_v1beta4_metadata_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDesc), len(file_google_cloud_sql_v1beta4_metadata_exchange_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_sql_v1beta4_metadata_exchange_proto_goTypes,
		DependencyIndexes: file_google_cloud_sql_v1beta4_metadata_exchange_proto_depIdxs,
		EnumInfos:         file_google_cloud_sql_v1beta4_metadata_exchange_proto_enumTypes,
		MessageInfos:      file_google_cloud_sql_v1beta4_metadata_exchange_proto_msgTypes,
	}.Build()
	File_google_cloud_sql_v1beta4_metadata_exchange_proto = out.File
	file_google_cloud_sql_v1beta4_metadata_exchange_proto_goTypes = nil
	file_google_cloud_sql_v1beta4_metadata_exchange_proto_depIdxs = nil
}
