// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: metadata_exchange.proto

package mdx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Indicates the socket-level protocol used by the database client, useful for
// the MySQL caching_sha2_password, which detects the socket type as part
// of the authentication protocol.
type MetadataExchangeRequest_ClientProtocolType int32

const (
	// Client protocol type is unspecified, TCP is used as default
	MetadataExchangeRequest_CLIENT_PROTOCOL_TYPE_UNSPECIFIED MetadataExchangeRequest_ClientProtocolType = 0
	// TCP socket connection, used for connections through the Auth Proxy
	// Client's TCP ports.
	MetadataExchangeRequest_TCP MetadataExchangeRequest_ClientProtocolType = 1
	// TLS socket over TCP, used in the connectors which pass an already
	// connected TCP socket with a complete handshake to the mysql driver.
	MetadataExchangeRequest_TLS MetadataExchangeRequest_ClientProtocolType = 2
	// Unix Domain socket connection, used for connections through the Auth
	// Proxy Client's unix sockets.
	MetadataExchangeRequest_UDS MetadataExchangeRequest_ClientProtocolType = 3
)

// Enum value maps for MetadataExchangeRequest_ClientProtocolType.
var (
	MetadataExchangeRequest_ClientProtocolType_name = map[int32]string{
		0: "CLIENT_PROTOCOL_TYPE_UNSPECIFIED",
		1: "TCP",
		2: "TLS",
		3: "UDS",
	}
	MetadataExchangeRequest_ClientProtocolType_value = map[string]int32{
		"CLIENT_PROTOCOL_TYPE_UNSPECIFIED": 0,
		"TCP":                              1,
		"TLS":                              2,
		"UDS":                              3,
	}
)

func (x MetadataExchangeRequest_ClientProtocolType) Enum() *MetadataExchangeRequest_ClientProtocolType {
	p := new(MetadataExchangeRequest_ClientProtocolType)
	*p = x
	return p
}

func (x MetadataExchangeRequest_ClientProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataExchangeRequest_ClientProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_exchange_proto_enumTypes[0].Descriptor()
}

func (MetadataExchangeRequest_ClientProtocolType) Type() protoreflect.EnumType {
	return &file_metadata_exchange_proto_enumTypes[0]
}

func (x MetadataExchangeRequest_ClientProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataExchangeRequest_ClientProtocolType.Descriptor instead.
func (MetadataExchangeRequest_ClientProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_metadata_exchange_proto_rawDescGZIP(), []int{0, 0}
}

// The status of the server metadata exchange.
type MetadataExchangeResponse_ResponseStatusCode int32

const (
	// Unknown response code
	MetadataExchangeResponse_RESPONSE_STATUS_CODE_UNSPECIFIED MetadataExchangeResponse_ResponseStatusCode = 0
	// Success
	MetadataExchangeResponse_OK MetadataExchangeResponse_ResponseStatusCode = 1
	// Failure
	MetadataExchangeResponse_ERROR MetadataExchangeResponse_ResponseStatusCode = 2
)

// Enum value maps for MetadataExchangeResponse_ResponseStatusCode.
var (
	MetadataExchangeResponse_ResponseStatusCode_name = map[int32]string{
		0: "RESPONSE_STATUS_CODE_UNSPECIFIED",
		1: "OK",
		2: "ERROR",
	}
	MetadataExchangeResponse_ResponseStatusCode_value = map[string]int32{
		"RESPONSE_STATUS_CODE_UNSPECIFIED": 0,
		"OK":                               1,
		"ERROR":                            2,
	}
)

func (x MetadataExchangeResponse_ResponseStatusCode) Enum() *MetadataExchangeResponse_ResponseStatusCode {
	p := new(MetadataExchangeResponse_ResponseStatusCode)
	*p = x
	return p
}

func (x MetadataExchangeResponse_ResponseStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataExchangeResponse_ResponseStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_exchange_proto_enumTypes[1].Descriptor()
}

func (MetadataExchangeResponse_ResponseStatusCode) Type() protoreflect.EnumType {
	return &file_metadata_exchange_proto_enumTypes[1]
}

func (x MetadataExchangeResponse_ResponseStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataExchangeResponse_ResponseStatusCode.Descriptor instead.
func (MetadataExchangeResponse_ResponseStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_metadata_exchange_proto_rawDescGZIP(), []int{1, 0}
}

// Message used by Cloud SQL connectors, including the Cloud SQL Auth Proxy and
// the Cloud SQL Language Connectors, to exchange client and connection
// metadata.
type MetadataExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User agent from the connector sending the request
	UserAgent *string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	// Client protocol type
	ClientProtocolType *MetadataExchangeRequest_ClientProtocolType `protobuf:"varint,2,opt,name=client_protocol_type,json=clientProtocolType,proto3,enum=mdx.MetadataExchangeRequest_ClientProtocolType,oneof" json:"client_protocol_type,omitempty"`
}

func (x *MetadataExchangeRequest) Reset() {
	*x = MetadataExchangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExchangeRequest) ProtoMessage() {}

func (x *MetadataExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExchangeRequest.ProtoReflect.Descriptor instead.
func (*MetadataExchangeRequest) Descriptor() ([]byte, []int) {
	return file_metadata_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataExchangeRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *MetadataExchangeRequest) GetClientProtocolType() MetadataExchangeRequest_ClientProtocolType {
	if x != nil && x.ClientProtocolType != nil {
		return *x.ClientProtocolType
	}
	return MetadataExchangeRequest_CLIENT_PROTOCOL_TYPE_UNSPECIFIED
}

// The response from the Cloud SQL instance back to the connector
// following an MetadataExchangeRequest.
type MetadataExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status code.
	ResponseStatusCode *MetadataExchangeResponse_ResponseStatusCode `protobuf:"varint,1,opt,name=response_status_code,json=responseStatusCode,proto3,enum=mdx.MetadataExchangeResponse_ResponseStatusCode,oneof" json:"response_status_code,omitempty"`
	// Error message.
	ErrorMessage *string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
}

func (x *MetadataExchangeResponse) Reset() {
	*x = MetadataExchangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataExchangeResponse) ProtoMessage() {}

func (x *MetadataExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataExchangeResponse.ProtoReflect.Descriptor instead.
func (*MetadataExchangeResponse) Descriptor() ([]byte, []int) {
	return file_metadata_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataExchangeResponse) GetResponseStatusCode() MetadataExchangeResponse_ResponseStatusCode {
	if x != nil && x.ResponseStatusCode != nil {
		return *x.ResponseStatusCode
	}
	return MetadataExchangeResponse_RESPONSE_STATUS_CODE_UNSPECIFIED
}

func (x *MetadataExchangeResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_metadata_exchange_proto protoreflect.FileDescriptor

var file_metadata_exchange_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x64, 0x78, 0x22, 0xa4,
	0x02, 0x0a, 0x17, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x66,
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x6d,
	0x64, 0x78, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01, 0x52,
	0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x22, 0x55, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x20,
	0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54,
	0x4c, 0x53, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x53, 0x10, 0x03, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x17, 0x0a, 0x15,
	0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa7, 0x02, 0x0a, 0x18, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x67, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x30, 0x2e, 0x6d, 0x64, 0x78, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x88, 0x01, 0x01, 0x22, 0x4d, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x20, 0x52,
	0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x10, 0x0a,
	0x0e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x46, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x73, 0x71, 0x6c, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x34, 0x42,
	0x1d, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x53, 0x71, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x64, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metadata_exchange_proto_rawDescOnce sync.Once
	file_metadata_exchange_proto_rawDescData = file_metadata_exchange_proto_rawDesc
)

func file_metadata_exchange_proto_rawDescGZIP() []byte {
	file_metadata_exchange_proto_rawDescOnce.Do(func() {
		file_metadata_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_metadata_exchange_proto_rawDescData)
	})
	return file_metadata_exchange_proto_rawDescData
}

var file_metadata_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metadata_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_exchange_proto_goTypes = []interface{}{
	(MetadataExchangeRequest_ClientProtocolType)(0),  // 0: mdx.MetadataExchangeRequest.ClientProtocolType
	(MetadataExchangeResponse_ResponseStatusCode)(0), // 1: mdx.MetadataExchangeResponse.ResponseStatusCode
	(*MetadataExchangeRequest)(nil),                  // 2: mdx.MetadataExchangeRequest
	(*MetadataExchangeResponse)(nil),                 // 3: mdx.MetadataExchangeResponse
}
var file_metadata_exchange_proto_depIdxs = []int32{
	0, // 0: mdx.MetadataExchangeRequest.client_protocol_type:type_name -> mdx.MetadataExchangeRequest.ClientProtocolType
	1, // 1: mdx.MetadataExchangeResponse.response_status_code:type_name -> mdx.MetadataExchangeResponse.ResponseStatusCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metadata_exchange_proto_init() }
func file_metadata_exchange_proto_init() {
	if File_metadata_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metadata_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataExchangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metadata_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataExchangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_metadata_exchange_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_metadata_exchange_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metadata_exchange_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_exchange_proto_goTypes,
		DependencyIndexes: file_metadata_exchange_proto_depIdxs,
		EnumInfos:         file_metadata_exchange_proto_enumTypes,
		MessageInfos:      file_metadata_exchange_proto_msgTypes,
	}.Build()
	File_metadata_exchange_proto = out.File
	file_metadata_exchange_proto_rawDesc = nil
	file_metadata_exchange_proto_goTypes = nil
	file_metadata_exchange_proto_depIdxs = nil
}
